// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: toe/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetNextGameIdRequest struct {
}

func (m *QueryGetNextGameIdRequest) Reset()         { *m = QueryGetNextGameIdRequest{} }
func (m *QueryGetNextGameIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNextGameIdRequest) ProtoMessage()    {}
func (*QueryGetNextGameIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{2}
}
func (m *QueryGetNextGameIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNextGameIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNextGameIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNextGameIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNextGameIdRequest.Merge(m, src)
}
func (m *QueryGetNextGameIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNextGameIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNextGameIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNextGameIdRequest proto.InternalMessageInfo

type QueryGetNextGameIdResponse struct {
	NextGameId NextGameId `protobuf:"bytes,1,opt,name=NextGameId,proto3" json:"NextGameId"`
}

func (m *QueryGetNextGameIdResponse) Reset()         { *m = QueryGetNextGameIdResponse{} }
func (m *QueryGetNextGameIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNextGameIdResponse) ProtoMessage()    {}
func (*QueryGetNextGameIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{3}
}
func (m *QueryGetNextGameIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNextGameIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNextGameIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNextGameIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNextGameIdResponse.Merge(m, src)
}
func (m *QueryGetNextGameIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNextGameIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNextGameIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNextGameIdResponse proto.InternalMessageInfo

func (m *QueryGetNextGameIdResponse) GetNextGameId() NextGameId {
	if m != nil {
		return m.NextGameId
	}
	return NextGameId{}
}

type QueryGetGameDataRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetGameDataRequest) Reset()         { *m = QueryGetGameDataRequest{} }
func (m *QueryGetGameDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetGameDataRequest) ProtoMessage()    {}
func (*QueryGetGameDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{4}
}
func (m *QueryGetGameDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGameDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGameDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGameDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGameDataRequest.Merge(m, src)
}
func (m *QueryGetGameDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGameDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGameDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGameDataRequest proto.InternalMessageInfo

func (m *QueryGetGameDataRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetGameDataResponse struct {
	GameData GameData `protobuf:"bytes,1,opt,name=gameData,proto3" json:"gameData"`
}

func (m *QueryGetGameDataResponse) Reset()         { *m = QueryGetGameDataResponse{} }
func (m *QueryGetGameDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetGameDataResponse) ProtoMessage()    {}
func (*QueryGetGameDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{5}
}
func (m *QueryGetGameDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGameDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGameDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGameDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGameDataResponse.Merge(m, src)
}
func (m *QueryGetGameDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGameDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGameDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGameDataResponse proto.InternalMessageInfo

func (m *QueryGetGameDataResponse) GetGameData() GameData {
	if m != nil {
		return m.GameData
	}
	return GameData{}
}

type QueryAllGameDataRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGameDataRequest) Reset()         { *m = QueryAllGameDataRequest{} }
func (m *QueryAllGameDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllGameDataRequest) ProtoMessage()    {}
func (*QueryAllGameDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{6}
}
func (m *QueryAllGameDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGameDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGameDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGameDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGameDataRequest.Merge(m, src)
}
func (m *QueryAllGameDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGameDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGameDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGameDataRequest proto.InternalMessageInfo

func (m *QueryAllGameDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllGameDataResponse struct {
	GameData   []GameData          `protobuf:"bytes,1,rep,name=gameData,proto3" json:"gameData"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGameDataResponse) Reset()         { *m = QueryAllGameDataResponse{} }
func (m *QueryAllGameDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllGameDataResponse) ProtoMessage()    {}
func (*QueryAllGameDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b285ee94ee213b73, []int{7}
}
func (m *QueryAllGameDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGameDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGameDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGameDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGameDataResponse.Merge(m, src)
}
func (m *QueryAllGameDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGameDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGameDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGameDataResponse proto.InternalMessageInfo

func (m *QueryAllGameDataResponse) GetGameData() []GameData {
	if m != nil {
		return m.GameData
	}
	return nil
}

func (m *QueryAllGameDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "avikj.toe.toe.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "avikj.toe.toe.QueryParamsResponse")
	proto.RegisterType((*QueryGetNextGameIdRequest)(nil), "avikj.toe.toe.QueryGetNextGameIdRequest")
	proto.RegisterType((*QueryGetNextGameIdResponse)(nil), "avikj.toe.toe.QueryGetNextGameIdResponse")
	proto.RegisterType((*QueryGetGameDataRequest)(nil), "avikj.toe.toe.QueryGetGameDataRequest")
	proto.RegisterType((*QueryGetGameDataResponse)(nil), "avikj.toe.toe.QueryGetGameDataResponse")
	proto.RegisterType((*QueryAllGameDataRequest)(nil), "avikj.toe.toe.QueryAllGameDataRequest")
	proto.RegisterType((*QueryAllGameDataResponse)(nil), "avikj.toe.toe.QueryAllGameDataResponse")
}

func init() { proto.RegisterFile("toe/query.proto", fileDescriptor_b285ee94ee213b73) }

var fileDescriptor_b285ee94ee213b73 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0xb3, 0xb5, 0x2d, 0xf5, 0x15, 0x51, 0xa6, 0xa9, 0x49, 0xb7, 0x76, 0x8d, 0x23, 0xb4,
	0xd1, 0xc3, 0x0e, 0x6d, 0x4f, 0x7a, 0x91, 0x16, 0x31, 0xe8, 0x41, 0x6a, 0xc0, 0x8b, 0x20, 0x65,
	0xd2, 0x0c, 0xeb, 0xea, 0xee, 0xce, 0x36, 0x3b, 0x29, 0x29, 0x22, 0x88, 0xa0, 0x17, 0x2f, 0x82,
	0x77, 0xff, 0x9e, 0x1e, 0x0b, 0x5e, 0x3c, 0x89, 0x24, 0xfe, 0x21, 0xb2, 0x33, 0x6f, 0x9b, 0xcd,
	0x66, 0x6b, 0xf5, 0x10, 0x48, 0xde, 0x7c, 0xef, 0xfb, 0x7e, 0x49, 0xbe, 0x59, 0xb8, 0xaa, 0xa4,
	0x60, 0x87, 0x7d, 0xd1, 0x3b, 0x76, 0xe3, 0x9e, 0x54, 0x92, 0x5c, 0xe1, 0x47, 0xfe, 0x9b, 0xd7,
	0xae, 0x92, 0x22, 0x7d, 0xd9, 0x55, 0x4f, 0x7a, 0x52, 0x9f, 0xb0, 0xf4, 0x9d, 0x11, 0xd9, 0x37,
	0x3c, 0x29, 0xbd, 0x40, 0x30, 0x1e, 0xfb, 0x8c, 0x47, 0x91, 0x54, 0x5c, 0xf9, 0x32, 0x4a, 0xf0,
	0xf4, 0xee, 0x81, 0x4c, 0x42, 0x99, 0xb0, 0x0e, 0x4f, 0xd0, 0x9b, 0x1d, 0x6d, 0x76, 0x84, 0xe2,
	0x9b, 0x2c, 0xe6, 0x9e, 0x1f, 0x69, 0x31, 0x6a, 0xaf, 0xa5, 0xf9, 0x31, 0xef, 0xf1, 0x30, 0xdb,
	0xbe, 0x9e, 0x4e, 0x22, 0x31, 0x50, 0xfb, 0x1e, 0x0f, 0xc5, 0xbe, 0xdf, 0xc5, 0xf9, 0x52, 0x3a,
	0xd7, 0xa3, 0x2e, 0x57, 0xdc, 0x0c, 0x69, 0x15, 0xc8, 0xb3, 0x34, 0x60, 0x4f, 0x3b, 0xb4, 0xc5,
	0x61, 0x5f, 0x24, 0x8a, 0x3e, 0x81, 0xa5, 0x89, 0x69, 0x12, 0xcb, 0x28, 0x11, 0x64, 0x1b, 0xe6,
	0x4d, 0x52, 0xdd, 0x6a, 0x58, 0xcd, 0xc5, 0xad, 0x65, 0x77, 0xe2, 0xbb, 0xba, 0x46, 0xbe, 0x3b,
	0x7b, 0xf2, 0xf3, 0x66, 0xa5, 0x8d, 0x52, 0xba, 0x0a, 0x2b, 0xda, 0xab, 0x25, 0xd4, 0x53, 0x31,
	0x50, 0x2d, 0x1e, 0x8a, 0xc7, 0xdd, 0x2c, 0xe8, 0x25, 0xd8, 0x65, 0x87, 0x98, 0xf7, 0x00, 0x60,
	0x3c, 0xc5, 0xcc, 0x95, 0x42, 0xe6, 0x58, 0x80, 0xb9, 0xb9, 0x15, 0xca, 0xa0, 0x96, 0xd9, 0xa7,
	0x93, 0x87, 0x5c, 0x71, 0x4c, 0x26, 0x55, 0x98, 0xf3, 0xa3, 0xae, 0x18, 0x68, 0xdb, 0xcb, 0x6d,
	0xf3, 0x81, 0x3e, 0x87, 0xfa, 0xf4, 0x02, 0xd2, 0xdc, 0x83, 0x05, 0x0f, 0x67, 0xc8, 0x52, 0x2b,
	0xb0, 0x64, 0x2b, 0x48, 0x72, 0x26, 0xa7, 0x1c, 0x39, 0x76, 0x82, 0xa0, 0xc8, 0xf1, 0x08, 0x60,
	0xfc, 0x9f, 0xa2, 0xef, 0xba, 0x6b, 0x0a, 0xe0, 0xa6, 0x05, 0x70, 0x4d, 0xb9, 0xb0, 0x00, 0xee,
	0x1e, 0xf7, 0x04, 0xee, 0xb6, 0x73, 0x9b, 0xf4, 0x9b, 0x85, 0xe8, 0x13, 0x19, 0xa5, 0xe8, 0x97,
	0xfe, 0x03, 0x9d, 0xb4, 0x26, 0xf8, 0x66, 0x34, 0xdf, 0xc6, 0x85, 0x7c, 0x26, 0x37, 0x0f, 0xb8,
	0xf5, 0x79, 0x16, 0xe6, 0x34, 0x20, 0x89, 0x60, 0xde, 0x34, 0x85, 0xdc, 0x2a, 0x50, 0x4c, 0x57,
	0xd1, 0xa6, 0x7f, 0x93, 0x98, 0x18, 0xba, 0xf6, 0xe1, 0xfb, 0xef, 0xaf, 0x33, 0x35, 0xb2, 0xcc,
	0xb4, 0x96, 0xa5, 0x45, 0x1f, 0x5f, 0x0b, 0xf2, 0xc9, 0xca, 0xf7, 0x88, 0x34, 0xcb, 0x1c, 0xcb,
	0xda, 0x69, 0xdf, 0xf9, 0x07, 0x25, 0x22, 0xdc, 0xd6, 0x08, 0x6b, 0x64, 0xb5, 0x80, 0x90, 0xbf,
	0x87, 0xe4, 0xa3, 0x05, 0x0b, 0xd9, 0x0f, 0x4d, 0xd6, 0xcf, 0x31, 0x2f, 0x14, 0xc4, 0xde, 0xb8,
	0x50, 0x87, 0x08, 0x4d, 0x8d, 0x40, 0x49, 0xa3, 0x80, 0x70, 0x76, 0xe5, 0xd9, 0x5b, 0x5d, 0xf2,
	0x77, 0xe4, 0xbd, 0x05, 0x8b, 0xd9, 0xfa, 0x4e, 0x10, 0x94, 0xa3, 0x4c, 0x77, 0xb5, 0x1c, 0xa5,
	0xa4, 0x6f, 0xb4, 0xa1, 0x51, 0x6c, 0x52, 0x3f, 0x0f, 0x65, 0xf7, 0xfe, 0xc9, 0xd0, 0xb1, 0x4e,
	0x87, 0x8e, 0xf5, 0x6b, 0xe8, 0x58, 0x5f, 0x46, 0x4e, 0xe5, 0x74, 0xe4, 0x54, 0x7e, 0x8c, 0x9c,
	0xca, 0x8b, 0x86, 0xe7, 0xab, 0x57, 0xfd, 0x8e, 0x7b, 0x20, 0xc3, 0xdc, 0xf6, 0xc0, 0x78, 0x1c,
	0xc7, 0x22, 0xe9, 0xcc, 0xeb, 0x47, 0xd7, 0xf6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x28,
	0x41, 0xbe, 0x7b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a NextGameId by index.
	NextGameId(ctx context.Context, in *QueryGetNextGameIdRequest, opts ...grpc.CallOption) (*QueryGetNextGameIdResponse, error)
	// Queries a GameData by index.
	GameData(ctx context.Context, in *QueryGetGameDataRequest, opts ...grpc.CallOption) (*QueryGetGameDataResponse, error)
	// Queries a list of GameData items.
	GameDataAll(ctx context.Context, in *QueryAllGameDataRequest, opts ...grpc.CallOption) (*QueryAllGameDataResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/avikj.toe.toe.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NextGameId(ctx context.Context, in *QueryGetNextGameIdRequest, opts ...grpc.CallOption) (*QueryGetNextGameIdResponse, error) {
	out := new(QueryGetNextGameIdResponse)
	err := c.cc.Invoke(ctx, "/avikj.toe.toe.Query/NextGameId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GameData(ctx context.Context, in *QueryGetGameDataRequest, opts ...grpc.CallOption) (*QueryGetGameDataResponse, error) {
	out := new(QueryGetGameDataResponse)
	err := c.cc.Invoke(ctx, "/avikj.toe.toe.Query/GameData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GameDataAll(ctx context.Context, in *QueryAllGameDataRequest, opts ...grpc.CallOption) (*QueryAllGameDataResponse, error) {
	out := new(QueryAllGameDataResponse)
	err := c.cc.Invoke(ctx, "/avikj.toe.toe.Query/GameDataAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a NextGameId by index.
	NextGameId(context.Context, *QueryGetNextGameIdRequest) (*QueryGetNextGameIdResponse, error)
	// Queries a GameData by index.
	GameData(context.Context, *QueryGetGameDataRequest) (*QueryGetGameDataResponse, error)
	// Queries a list of GameData items.
	GameDataAll(context.Context, *QueryAllGameDataRequest) (*QueryAllGameDataResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) NextGameId(ctx context.Context, req *QueryGetNextGameIdRequest) (*QueryGetNextGameIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextGameId not implemented")
}
func (*UnimplementedQueryServer) GameData(ctx context.Context, req *QueryGetGameDataRequest) (*QueryGetGameDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameData not implemented")
}
func (*UnimplementedQueryServer) GameDataAll(ctx context.Context, req *QueryAllGameDataRequest) (*QueryAllGameDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameDataAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avikj.toe.toe.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NextGameId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNextGameIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NextGameId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avikj.toe.toe.Query/NextGameId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NextGameId(ctx, req.(*QueryGetNextGameIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GameData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGameDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GameData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avikj.toe.toe.Query/GameData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GameData(ctx, req.(*QueryGetGameDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GameDataAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGameDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GameDataAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avikj.toe.toe.Query/GameDataAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GameDataAll(ctx, req.(*QueryAllGameDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "avikj.toe.toe.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "NextGameId",
			Handler:    _Query_NextGameId_Handler,
		},
		{
			MethodName: "GameData",
			Handler:    _Query_GameData_Handler,
		},
		{
			MethodName: "GameDataAll",
			Handler:    _Query_GameDataAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "toe/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNextGameIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNextGameIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNextGameIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetNextGameIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNextGameIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNextGameIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NextGameId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetGameDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGameDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGameDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetGameDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGameDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGameDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.GameData.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllGameDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGameDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGameDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllGameDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGameDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGameDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.GameData) > 0 {
		for iNdEx := len(m.GameData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GameData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNextGameIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetNextGameIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NextGameId.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetGameDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetGameDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.GameData.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllGameDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllGameDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GameData) > 0 {
		for _, e := range m.GameData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNextGameIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNextGameIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNextGameIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNextGameIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNextGameIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNextGameIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextGameId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NextGameId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGameDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGameDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGameDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGameDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGameDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGameDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GameData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGameDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGameDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGameDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGameDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGameDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGameDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameData = append(m.GameData, GameData{})
			if err := m.GameData[len(m.GameData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
